name: 'Get next `Kiri Ban`'
description: 'Get the next `Kiri Ban`'
author: 'amyu'

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false

outputs:
  next:
    description: Number of remaining until the next 'Kiri ban'

runs:
  using: 'node16'
  main: 'dist/index.js'
