name: 'build-test'
on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./
        id: kiri

      - run: echo "The number remaining until the next 'Kiri Ban' is  ${{ steps.kiri.outputs.next }}"
